# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/home/yayu/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="half-life"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

### alias
alias grep=egrep
alias grep='grep --color=always -n '
alias 'ps?'='ps ax | grep '
alias 'h?'='history|grep '
alias "wcc"="awk -F'|' '{print NF; exit}'"

### colorfule manpage
export LESS_TERMCAP_mb=$'\E[05;34m' # begin blinking
export LESS_TERMCAP_md=$'\E[01;34m' # begin bold
export LESS_TERMCAP_me=$'\E[0m'     # end mode
export LESS_TERMCAP_se=$'\E[0m'     # end standout-mode
export LESS_TERMCAP_so=$'\E[44;33m' # begin standout-mode
export LESS_TERMCAP_ue=$'\E[0m'     # end underline
export LESS_TERMCAP_us=$'\E[04;33m' # begin underline

### editor
export EDITOR=vim


# functions
extract() {
  if [ -f $1 ]; then
    case $1 in
      *.tar.bz2) tar xjf $1 ;;
      *.tar.gz) tar xzf $1 ;;
      *.bz2) bunzip2 $1 ;;
      *.rar) unrar e $1 ;;
      *.gz) gunzip $1 ;;
      *.tar) tar xf $1 ;;
      *.tbz2) tar xjf $1 ;;
      *.tgz) tar xzf $1 ;;
      *.zip) unzip $1 ;;
      *.Z) uncompress $1 ;;
      *.7z) 7z x $1 ;;
      *) echo "'$1' cannot be extracted via extract()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

function mcd() {
  mkdir -p "$1" && cd "$1"
}

# go back x directories
b() {
  str=""
  count=0
  while [ "$count" -lt "$1" ]; do
    str=$str"../"
    let count=count+1
  done
  cd $str
}

# alias
## recursive  directory listing.
alias lr='ls -R | grep ":$" | sed -e '\''s/:$//'\'' -e '\''s/[^-][^\/]*\//--/g'\'' -e '\''s/^/   /'\'' -e '\''s/-/|/'\'''
## lsd
alias l='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias lt='ls --tree'


alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../../'
alias .....='cd ../../../../'
alias ......='cd ../../../../../'

## show hidden files only
alias l.='ls -d .* --color=auto'
## List files in human readable format with color and without implied directories
alias l='ls -lAh --color'
## List all folders
alias lf='ls -Gl | grep ^d'   #Only list directories
alias ll="ls -al"

setopt extended_glob

test -e ~/.rvm/scripts/rvm && source ~/.rvm/scripts/rvm

export GH=$GOPATH/src/github.com

export PATH=$GOPATH/bin:$PATH

### syntax-highlight
SH_FILE=/usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
if [ -f "$SH_FILE" ]; then
  source $SH_FILE
fi

### git
alias gad="git add --all ."
alias gpom="git push origin master"
alias gcom="git commit -am "
alias gu='git add --all . && git commit -am "Update" && git push origin'
alias gm1='git commit -am "1"'
alias rel="git checkout release"
alias gbd='git branch -D '
alias glf='git --no-pager log --decorate=short --pretty=oneline -n1'
alias glp="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"

## new comand
alias fuck='$(thefuck $(fc -ln -1))'

test -f ~/.private_zsh_env && source ~/.private_zsh_env


### dirs
alias ag="ag"
alias vi="vim"



## locale
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Setting for the new UTF-8 terminal support in Lion
LC_CTYPE=en_US.UTF-8
LC_ALL=en_US.UTF-8


[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh




## dirs
export dcp=~/Golang/src/github.com/alauda/captain
export PATH=$GOROOT/bin:$PATH
export GOPATH=$HOME/Golang
export PATH=$GOPATH/bin:$PATH
export PATH=/usr/loca/bin:$PATH
# export GOPROXY=https://gocenter.io

export PATH=$PATH:/usr/local/kubebuilder/bin
export PATH=$PATH:~/Soft/GoLand-2018.3.6/bin

export PATH=/home/yayu/Soft/GoLand-2018.3.6/bin:$PATH

# https://github.com/mollifier/cd-bookmark
# source /usr/local/share/antigen/antigen.zsh
#alias cdb='cd-bookmark'


[ -f ~/Config/lib/z.sh ] && . ~/Config/lib/z.sh

# docker
export DOCKER_CLI_EXPERIMENTAL=enabled
# Install Ruby Gems to ~/gems
export GEM_HOME="$HOME/gems"
export PATH="$HOME/gems/bin:$PATH"

# pbcopy on linux
alias pbcopy='xsel --clipboard --input'
alias pbpaste='xsel --clipboard --output'


# kubectl
autoload -U +X compinit && compinit
[ -f /opt/bin/kubectl ] && source <(kubectl completion zsh)

# shortcut for http proxy
alias set_proxy='export http_proxy=http://127.0.0.1:1081/'
alias unset_proxy='unset http_proxy'

# pip path
export PATH=$PATH:~/.local/bin/

# golang
export GO111MODULE=on


# local kubernetes bins
export PATH=/opt/bin:/opt/cni/bin:$PATH
